CREATE TABLE IF NOT EXISTS `oauth2_client` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(80) NOT NULL,
    `secret` VARCHAR(80),
    `redirect` TEXT,
    `grant_type` TEXT,
    `scope` TEXT,
    `user` INTEGER,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `oauth2_access_token` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `access_token` VARCHAR(40) NOT NULL UNIQUE,
    `client` INTEGER NOT NULL,
    `user` INTEGER,
    `scope` TEXT,
    `expires` DATETIME,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `oauth2_authorization_code` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `authorization_code` VARCHAR(40) NOT NULL UNIQUE,
    `client` INTEGER NOT NULL,
    `user` INTEGER,
    `redirect` TEXT,
    `scope` TEXT,
    `id_token` TEXT,
    `expires` DATETIME,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `oauth2_refresh_token` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `refresh_token` VARCHAR(40) NOT NULL UNIQUE,
    `client` INTEGER NOT NULL,
    `user` INTEGER,
    `scope` TEXT,
    `expires` DATETIME,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `oauth2_user` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user` INTEGER NOT NULL,
    `scope` TEXT,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `oauth2_scope` (
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(80) NOT NULL UNIQUE,
    `default` BOOLEAN DEFAULT FALSE,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);